// <auto-generated />
namespace BloodDonorApp.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserTypesChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTypesChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201912072147378_UserTypesChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
